### ISSUE TITLE
Make Content Immediately Visible

### ISSUE THREAD

**Issue by lazaridiscom** [tacoinfra/developers.tezos.com#38]
One of the greatest annoyances of tezos related sites is that one has to scroll down to reach the relevant content. Especially a newcomer must do this again and again.

To make https://developers.tezos.com/ a bit more convenient:

* Remove the duplicated reddit/matrix/stackexchange links in the the header
* Move "developer mailing list" to the footer
* Rename "Tezos Developer Portal" to "Tezos Developer Resources"
* remove "Resources for Developers"
* Shrink the height of the blue header to the minimum necessary

=> ready.

This 1st batch of tiny changes will make the "Getting Started"  entries immediately visible when landing on the page.

**Comment by SarahFowler73** [comment]
We would welcome a PR with your ideas

**Comment by lazaridiscom** [comment]
I'll give it a try.
