### ISSUE TITLE
Simplify "Digital Assets on Tezos" Intro

### ISSUE THREAD

**Issue by lazaridiscom** [tacoinfra/developers.tezos.com#41]
(initially filed within: https://gitlab.com/tezos/tezos/issues/676, please review for some "grand-scope" background info)

## Status

https://assets.tqtezos.com/setup/1-tezos-client

## Expected

Simplify this, possibly drastically, so it can be executed by

* non-devs
* devs which are tired
* evaluators which are bored

This can be achieved by

* rewriting the page (naturally by a person with simplification skills)
* trivial changes within the projects

Where are the sources of https://assets.tqtezos.com located?

## Off-Repo Note

I could not find a TQtezos repo, the closest relevant repo is this here (developers.tezos.com links to the "Digital Assets on Tezos" Intro)

**Comment by SarahFowler73** [comment]
I'm curious why the tutorial from the developer portal should be rewritten to target non-devs. That getting started tutorial is meant to be a helpful first interaction with the tezos-client that is simpler than reading through the official documentation, but is not meant to _be_ official documentation. More non-dev-friendly interactions with the chain are through tools like LIGO and SmartPy.

Just a reminder that tools and resources linked to by this site are not _controlled_ by this site or by Tezos foundation.

**Comment by lazaridiscom** [comment]
To avoid redundant effort on both sides:

closing, due to different mentalities, see comment: https://github.com/tacoinfra/developers.tezos.com/pull/40#issuecomment-582568270

**Comment by lazaridiscom** [comment]
To cover your curiosity:

> I'm curious why the tutorial from the developer portal should be rewritten to target non-devs.

If "non-dev" simplicity is achievable (of course without adding noisy explanations, which would annoy devs) then provide it. This way, "devs which are tired" can still get through, similar to "evaluators which are bored".

**Comment by SarahFowler73** [comment]
I think the issue is that with the client, non-dev simplicity is not achievable. There are developers working on tools currently to simplify interactions, but some of it is a little manual to start. 

I'm happy to have a conversation about your feedback. No need to close all your issues.

**Comment by lazaridiscom** [comment]
It is achievable, with the right mentality and lead.

The effort to discuss/rework is many times higher than a rewrite from scratch.

More within https://github.com/tacoinfra/developers.tezos.com/pull/40#issuecomment-582769455
